### ISSUE TITLE
Inputs on CLI get printed twice

### ISSUE THREAD

**Issue by minnn-minnn** [charleskorn/batect#21] opened 2018-11-15 03:45 UTC
Issue discovered when sshed onto a docker container started by batect (bash).  Typed commands look like I have very shaky hands/or too much coffee.

```
e.g. make -> mmaakkee
```

It's pretty hard to read. 

Batect version: 0.23
Container Image: Alpine 3.8

**Comment by charleskorn** [comment] 2018-11-15 05:07
Thanks for the bug report @minnn-minnn.

Just to confirm, you're running `bash` inside a container (which is using `alpine:3.8`), and then SSHing into the container? 

Could you perhaps send me a sample `batect.yml` and the commands you're running so that I can reproduce the problem here?

**Comment by minnn-minnn** [comment] 2018-11-15 06:09
> Just to confirm, you're running bash inside a container (which is using alpine:3.8), and then SSHing into the container?

Yup. 

> Could you perhaps send me a sample batect.yml and the commands you're running so that I can reproduce the problem here?

I'll send you an email

**Comment by charleskorn** [comment] 2018-11-15 06:13
Thanks!

**Comment by charleskorn** [comment] 2018-11-19 23:29
Further offline discussion has revealed that SSH is not involved (this happens when running `./batect the-task`)

I can't reproduce this issue at the moment and @minnn-minnn is going to try to isolate the problem so I can reproduce it.

**Comment by ineffyble** [comment] 2018-11-28 04:12
I'm now working with @minnn-minnn and have worked out that this bug was introduced in 0.22.0. Previous versions work fine. Hope this helps narrow the problem down.

**Comment by charleskorn** [comment] 2018-11-28 23:16
Alright, that tells me where the problem is but I don't understand why it's happening. Does this affect all containers you run, or just this one? (I can't reproduce the problem locally at the moment, so I need some help to narrow it down so that I can.)

**Comment by charleskorn** [comment] 2018-11-29 00:15
Further details from @minnn-minnn:

> Centos Linux 7 - kernel: linux 3.10.0 x86_64
> Bash - 4.4.19

**Comment by charleskorn** [comment] 2018-11-30 01:35
I can now reproduce this problem! Thanks for your help @minnn-minnn and @ineffyble. I'll take a look and see what the fix is.

**Comment by charleskorn** [comment] 2018-11-30 02:32
Resolved with 6b593a8.

Thanks for your help and patience @minnn-minnn and @ineffyble!

**Closed by charleskorn** 2018-11-30 02:32 UTC
Labels: bug
