### ISSUE TITLE
build succeeds/fails when running multiple times in a row

### ISSUE THREAD

**Issue by binkley** [charleskorn/batect#51] opened 2019-01-11 10:58 UTC
In project https://github.com/binkley/docker-java11, at commit `4194e19f64c1bd5dde56117badc139c6d52060b5`, I can reproduce alternating success/failure with (output elided):
```
$ ./batect build
$ ./batect build
$ ./batect build
$ ./batect build
```
Failure looks like:
```
BUILD SUCCESSFUL in 15s
3 actionable tasks: 3 up-to-date

Error: An unexpected exception occurred during execution.
java.lang.RuntimeException: Invoking 'stty 6b02:3:4b00:200005cb:4:ff:ff:7f:17:15:12:ff:3:1c:1a:19:11:13:16:f:1:0:14:ff' failed with exit code 1: stty: 'standard input': unable to perform all requested operations

Clean up: done

The task build failed. See above for details.
```

**Comment by charleskorn** [comment] 2019-01-13 01:46
This looks like a duplicate of #46 (albeit with a reproduction) - are you ok for me to close #46 and work in here?

**Comment by charleskorn** [comment] 2019-01-13 01:47
To help me diagnose the issue, I need a little more information:

1. Can you please try running `stty -g` and then `stty <output from stty -g>` outside of batect (ie. in a standard Bash shell) - do you see the same error? 
  
   (So if `stty -g` gives you `abc123:456`, please run `stty abc123:456` as the second command.)

2. What OS are you running? And if you're running Linux, what distro and version are you using?

**Comment by charleskorn** [comment] 2019-01-18 23:45
One last question... can you please run `which stty`? 

(Based on https://github.com/alexch/rerun/issues/62 and the non-standard output you're getting from `stty`, I suspect you might have a different version of `stty` on your path.)

**Comment by charleskorn** [comment] 2019-04-11 23:05
I'm going to close this due to inactivity - if you're able to share more info, I'm happy to reopen this and take a look.

**Closed by charleskorn** 2019-04-11 23:05 UTC
Labels: bug, waiting for more info
