### ISSUE TITLE
UnsupportedOperationException when running on Java 9

### ISSUE THREAD

**Issue by assafw** [charleskorn/batect#1] opened 2017-11-03 05:38 UTC
when trying to run `batect -v`
the output is:
`java.lang.UnsupportedOperationException: Retrieving groups by name is not supported on this platform.`

**Comment by charleskorn** [comment] 2017-11-03 05:39
Thanks for the bug report Assaf! I don't have much time to look at this this weekend, but I'll take a look next week.

Could you please send me the exact version of Java you're using (eg. run `java -version`)?

**Comment by assafw** [comment] 2017-11-05 23:20
No worries Charles, happy to help :)

output from 1.9 'java -version' command:

java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)

Cheers,

  -- Assaf

**Comment by charleskorn** [comment] 2017-11-09 03:32
This looks like an issue in Kotlin's stdlib when running on Java 9: https://youtrack.jetbrains.com/issue/KT-20865

The Kotlin team is aware of the issue and working on a fix, so it seems that there's not much value in me spending time on adding a temporary workaround. For the time being, please use Java 8. 

I'll add a note to the release notes so people are aware of this problem and leave this issue open until the issue is fixed by the Kotlin team.

Thanks for reporting this issue!

**Comment by charleskorn** [comment] 2017-11-27 09:34
I've added a workaround for this, and it'll be included in the upcoming 0.7 release.

Thanks again for reporting this issue!

**Closed by charleskorn** 2017-11-27 09:34 UTC
Labels: bug, issue with dependency
